# Generated by Django 4.1.5 on 2023-01-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='womenpost',
            name='img',
            field=models.ImageField(null=True, upload_to='WomanPostImg'),
        ),
    ]
